version: 2

models:
 
  - name: stg_pharma_products
    description: "Cleaned staging view of pharma products"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      
      - name: product_price
        tests:
          - not_null
      
      - name: category_type
        tests:
          - accepted_values:
              values: ['other', 'analgesic', 'antibiotic', 'antihistamine', 'antihypertensive', 'corticosteroid', 'antacid', 
              'bronchodilator', 'antidepressant', 'antidiabetic', 'diuretic']

      - name: dosage_form
        tests:
          - accepted_values:
              values: ['capsule','cream','drops','gel','inhaler','injection','ointment','other','powder','respules','solution','spray','suspension','syrup','tablet','False']
  
  - name: dim_price
    description: "Subset of columns with specific information"